Repository AcclaroInc/craft-translations, pull requests merged in 2022-08, with the labels that each got.

#375 fix: category draft non localised blocks issue and code refactor
  src/controllers/AssetController.php
  src/controllers/CategoryController.php
  src/services/repository/FileRepository.php
  src/templates/assets/_editDraft.twig
  src/templates/categories/_editDraft.twig
  src/templates/globals/_editDraft.twig
Labels: awaiting code review

#376 Fix category draft issue and refactor
  src/assetbundles/src/js/OrderEntries.js
  src/elements/Order.php
  src/services/repository/OrderRepository.php
  src/templates/orders/_detail.twig
Labels: awaiting code review

#365 Release/2.2.3
  .craftplugin
  CHANGELOG.md
  src/Constants.php
  src/Translations.php
  src/assetbundles/src/js/OrderEntries.js
  src/controllers/AssetController.php
  src/controllers/BaseController.php
  src/controllers/CategoryController.php
  src/controllers/FilesController.php
  src/controllers/OrderController.php
  src/controllers/SettingsController.php
  src/controllers/WidgetController.php
  src/elements/Order.php
  src/models/FileModel.php
  src/services/App.php
  src/services/ElementToFileConverter.php
  src/services/LogHelper.php
  src/services/api/AcclaroApiClient.php
  src/services/api/CraftApiClient.php
  src/services/fieldtranslator/AssetsFieldTranslator.php
  src/services/fieldtranslator/GenericFieldTranslator.php
  src/services/fieldtranslator/MatrixFieldTranslator.php
  src/services/fieldtranslator/NeoFieldTranslator.php
  src/services/fieldtranslator/SeomaticMetaFieldTranslator.php
  src/services/fieldtranslator/SuperTableFieldTranslator.php
  src/services/job/ImportFiles.php
  src/services/repository/AssetDraftRepository.php
  src/services/repository/CategoryDraftRepository.php
  src/services/repository/CategoryRepository.php
  src/services/repository/DraftRepository.php
  src/services/repository/EntryRepository.php
  src/services/repository/FileRepository.php
  src/services/repository/GlobalSetDraftRepository.php
  src/services/repository/GlobalSetRepository.php
  src/services/repository/OrderRepository.php
  src/services/repository/TagRepository.php
  src/services/repository/TranslationRepository.php
  src/services/repository/TranslatorRepository.php
  src/services/translator/AcclaroTranslationService.php
  src/services/translator/Export_ImportTranslationService.php
  src/templates/_components/orders/info-tab.twig
  src/templates/assets/_editDraft.twig
  src/templates/categories/_editDraft.twig
  src/templates/globals/_editDraft.twig
  src/templates/orders/_detail.twig
Labels: do not merge

#366 Feature/quote request for api order
  src/Constants.php
  src/assetbundles/FilePreviewAssets.php
  src/assetbundles/src/css/FilePreview.css
  src/assetbundles/src/css/Translations.css
  src/assetbundles/src/js/AssetsTranslations.js
  src/assetbundles/src/js/EntryPreview.js
  src/assetbundles/src/js/OrderDetails.js
  src/base/PluginTrait.php
  src/controllers/FilesController.php
  src/controllers/OrderController.php
  src/elements/Order.php
  src/migrations/Install.php
  src/migrations/m220708_101407_add_request_quote_column_to_orders_table.php
  src/models/FileModel.php
  src/services/api/AcclaroApiClient.php
  src/services/fieldtranslator/AssetsFieldTranslator.php
  src/services/fieldtranslator/MatrixFieldTranslator.php
  src/services/fieldtranslator/NeoFieldTranslator.php
  src/services/fieldtranslator/SuperTableFieldTranslator.php
  src/services/repository/AssetDraftRepository.php
  src/services/repository/FileRepository.php
  src/services/repository/OrderRepository.php
  src/services/translator/AcclaroTranslationService.php
  src/templates/_components/_forms/order-entries-table.twig
  src/templates/_components/_forms/order-files-table.twig
  src/templates/_components/_forms/order-quote-table.twig
  src/templates/_components/orders/files-tab.twig
  src/templates/_components/orders/quote-tab.twig
  src/templates/_components/orders/settings-tab.twig
  src/templates/orders/_detail.twig
Labels: enhancement, awaiting code review

#380 Update: Order quote feedback changes
  src/assetbundles/FilePreviewAssets.php
  src/assetbundles/src/css/FilePreview.css
  src/assetbundles/src/js/FilePreview.js
  src/assetbundles/src/js/OrderDetails.js
  src/controllers/FilesController.php
  src/controllers/OrderController.php
  src/templates/_components/_forms/order-files-table.twig
  src/templates/_components/_forms/order-quote-table.twig
  src/templates/_components/orders/quote-tab.twig
Labels: awaiting code review

#381 Fix/release3.0.0/feedbacks
  src/assetbundles/src/css/Translations.css
  src/assetbundles/src/js/EntryPreview.js
  src/assetbundles/src/js/FilePreview.js
  src/assetbundles/src/js/OrderEntries.js
  src/services/repository/FileRepository.php
  src/templates/_components/_forms/order-entries-table.twig
  src/templates/_components/_forms/order-files-table.twig
Labels: awaiting code review

#385 fix: missing preview content
  src/templates/_components/_forms/order-files-table.twig
Labels: awaiting code review
